name: Issue Triage
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  issue-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carbon-design-system/carbon
      
      - uses: carbon-design-system/carbon/.github/workflows/issue-triage.yml@main
        with:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
